version: '3.8'

x-common-variables: &common-env
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_RESULT_BACKEND: redis://redis:6379/0
  STABLE_API_URL: https://d754-34-124-135-196.ngrok-free.app/

services:

  web:
    build: .
    ports:
      - 8000:8000
    command: fastapi dev --host 0.0.0.0 --port 8000
    environment:
      <<: *common-env
    depends_on:
      - redis
    volumes:
      - .:/app

  worker:
    build: .
    command: celery -A workers.celery_app worker --loglevel=info
    environment:
      <<: *common-env
    depends_on:
      - web
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:latest

  dashboard:
    build: .
    command: celery --broker=redis://redis:6379/0 flower
    ports:
      - 5555:5555
    environment:
      <<: *common-env
    depends_on:
      - web
      - redis
      - worker
